crm/urls.py
from . import views

from django.urls import path
from django.views.generic.base import TemplateView


app_name = 'crm'

urlpatterns = [
    path('crm/leads', views.leads, name='leads'),
    path('crm/unsubscrib/<email>/<code>', views.unsubscrib, name='unsubscrib'),
    path('crm/subscrib/<str:email>', views.subscrib, name='subscrib'),
]

evaluation/urls.py
from django.urls import path
from . import views

app_name = 'evaluation'
urlpatterns = [
    path('evaluation/', views.eva_index, name='evaluation'),    
    path('evaluation/option_add/', views.option_add, name='option_add'),  
    path('evaluation/option_append/', views.option_append, name='option_append'),
    path('evaluation/thanks/', views.thanks, name='thanks'),      
    path('evaluation/report/<int:report_id>', views.report, name='report'),         
    
    
]

home/urls.py
from . import views

from django.urls import path
from django.views.generic.base import TemplateView


app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/settings/', views.user_setting, name='user_settings'),
    path('dashboard/change_pass/', views.password_change, name='change_pass'),
    path('dashboard/questions/', views.questions, name='questions'),
    path('dashboard/questions/<str:pk>', views.questions_details, name='questions_details'), 
    path('dashboard/allreports/', views.allreports, name='all_reports'),  
    path('dashboard/new_questions/', views.new_questions, name='new_question'),
]

hx_urlpatterns = [
    
    path('check_type_to_get_expert/', views.check_type_to_get_expert, name='check_type_to_get_expert'),
    path('dashboard/add_extra/<str:pk>', views.add_extra, name='add_extra'),
    path('dashboard/sub_extra/<str:pk>', views.sub_extra, name='sub_extra'),
    
]

urlpatterns += hx_urlpatterns

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from accounts.models import User, Profile
from evaluation.models import Question, Option

from django.contrib.auth.forms import PasswordChangeForm


class PasswordChangeForm(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].widget = forms.PasswordInput(attrs={'autocomplete': 'current-password', 'autofocus': True, 'class':'form-control'})
        self.fields['new_password1'].widget = forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class':'form-control'})
        self.fields['new_password2'].widget = forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class':'form-control'})
        





class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','first_name', 'last_name', 'email', 'orgonization', 'phone', )
        
        widgets = {
                      
            'username': forms.TextInput(attrs={'placeholder': 'username', 'class':'form-control', 'aria-label':'username',  }),
            'first_name': forms.TextInput(attrs={'placeholder': 'first_name', 'class':'form-control', 'aria-label':'first_name' }),
            'last_name': forms.TextInput(attrs={'placeholder': 'last_name','class':'form-control', 'aria-label':'last_name', }), 
            'orgonization': forms.TextInput(attrs={'placeholder': 'orgonization','class':'form-control', 'aria-label':'orgonization', }), 
            'phone': forms.TextInput(attrs={'placeholder': 'phone','class':'form-control', 'aria-label':'phone', }), 
            'email': forms.EmailInput(attrs={'placeholder': 'email', 'class':'form-control', 'aria-label':'email' , }),
            
            
        }
        labels = {     
                     
            'username':'Username',
            'first_name':'First name',
            'first_name':'Last Name',
            'orgonization':'Orgonization',
            'phone':'Phone',
            'email': 'Email',
            
        }
        
        
   
        
class ProfileForm(forms.ModelForm):
    class Meta:
        
        
        model = Profile
        fields = ('about','location','established',)
        
        widgets = {
                      
            'about': forms.Textarea(attrs={'placeholder': 'about', 'class':'form-control', 'aria-label':'about' }),
            'location': forms.TextInput(attrs={'placeholder': 'location', 'class':'form-control', 'aria-label':'location' }),
            'established': forms.DateInput(attrs={'data-datepicker': "" , 'class':'form-control', 'aria-label':'established', }), 
            
            
        }
        labels = {     
                     
            'about': 'About',
            'location': 'Location',
            'established': 'Established',           
            
        }
        
class QuestionForm(forms.ModelForm):
    class Meta:
        model   = Question
        fields  = ('name',)
        widgets = {
                      
            'name': forms.TextInput(attrs={'placeholder': 'name', 'class':'form-control', 'aria-label':'name' }),          
            
            
        }
        
        labels = {     
                     
            'name': 'Edit Question',
            
                     
        }
        

class OptionForm(forms.ModelForm):
    class Meta:
        model   = Option
        fields  = ('name', 'statement', )
        widgets = {
                      
            'name': forms.TextInput(attrs={'placeholder': 'name', 'class':'form-control', 'aria-label':'name' }),
            'statement': forms.Textarea(attrs={'placeholder': 'statement', 'class':'form-control', 'aria-label':'statement' }),      
            
            
        }
        
        labels = {     
                     
            'name': 'Option Label',
            'statement': 'Option Statement',
                     
        }
        
    

        
       
  
  
        
  
  
       

home/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpRequest, HttpResponse, HttpResponseNotAllowed, HttpResponseRedirect
from .forms import UserForm, ProfileForm, PasswordChangeForm, QuestionForm, OptionForm
from django.contrib import messages
from django.urls import reverse, reverse_lazy
# from django.contrib.auth.forms import PasswordChangeForm
from accounts.decorators import expert_required, producer_required, consumer_required
from accounts.models import User, UserType
from accounts.helper import check_type
from gfvp import null_session
from django.contrib.auth import update_session_auth_hash
from django.shortcuts import redirect, render, get_object_or_404
from evaluation.models import *
from django.forms import formset_factory, inlineformset_factory
from django.core.exceptions import PermissionDenied
from .helper import users_under_each_label, reports_under_each_biofuel, weeks_results, all_reports, total_reports, typewise_user
from django.db.models import Count, Min


def home(request):
    null_session(request)
    
    user_types = UserType.objects.filter(active = True).order_by('sort_order') 
    context = {
        'user_types': user_types        
    }
    return render(request, 'home/index.html', context = context)


def user_types(request, slug):
    null_session(request)    
    request.session['interested_in'] = slug   
    
    '''Same type of user and admin and staff can have permission to visit this page'''
    
    # check_type(request, slug)
    try:
        curent_user_type_slug = request.user.type.slug
    except:
        curent_user_type_slug = None
        
    
    if slug == curent_user_type_slug:        
        enroll = reverse('evaluation:evaluation')
    else:
        enroll = ''
        
    try:
        user_type = UserType.objects.get(slug = slug)
        users = User.objects.filter(type = user_type)
    except:
        user_type = None
        users = None
    
    context = {
        'user_type': user_type,
        'users': users,
        'enroll': enroll    
    }
    return render(request, 'home/usertypes.html', context = context)
    


@login_required
def dashboard(request):
    null_session(request)    
    day_of_week = [key.split(': ') for key, value in weeks_results(request).items()]
    total_of_day = [value for key, value in weeks_results(request).items()]
    
    # print(typewise_user(request))
    
    
    
    context = {
        'user_of_labels' : users_under_each_label(request),
        'biofuel_records' : reports_under_each_biofuel(request),
        'day_of_week': day_of_week,
        'total_of_day': total_of_day,  
        'total_reports': total_reports(request),      
        'allreports' : all_reports(request),
        'typewise_user' : typewise_user(request)
        
    }
    
    
    
    return render(request, 'home/dashboard.html', context = context)

@login_required
def user_setting(request):   
    null_session(request) 
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        
        if user_form.is_valid():
            user_form.save()
            messages.success(request,('Your profile was successfully updated!'))		    
        elif profile_form.is_valid():
            profile_form.save()
            messages.success(request,('Your profile data was successfully updated!'))
        else:
            messages.error(request, 'Invalid form submission.')
            messages.error(request, profile_form.errors)
            messages.error(request, user_form.errors) 
           
        
        return HttpResponseRedirect(reverse('home:user_settings'))
    user_form = UserForm(instance=request.user)
    profile_form = ProfileForm(instance=request.user.profile)    
    
    context = {
        "user":request.user,
        "user_form":user_form,
        "profile_form":profile_form,
        
    }
    return render(request, 'home/settings.html', context = context)

@login_required
def password_change(request):   
    null_session(request) 
    if request.method == "POST":        
        password_form = PasswordChangeForm(user=request.user, data=request.POST)        
        if password_form.is_valid():            
            password_form.save()            
            update_session_auth_hash(request, password_form.user)            
            messages.success(request,('Your password was successfully updated!')) 
        else:
            messages.error(request, 'Invalid form submission.')            
            messages.error(request, password_form.errors)       
        
        return HttpResponseRedirect(reverse('home:change_pass'))
    
    password_form = PasswordChangeForm(request.user)  
    
    context = {
        "user":request.user,        
        "password_form":password_form
    }
    return render(request, 'home/change_pass.html', context = context)



@login_required
@expert_required
def questions(request):  
    null_session(request)
    '''get questions related to the current user'''
    curent_user_expert_in = request.user.experts_in
    label_to_question = Label.objects.filter(name = curent_user_expert_in, value = str(1))
    
    if request.user.is_staff or request.user.is_superuser:
        questions = Question.objects.all()
    else:    
        questions = []
        for q in label_to_question:
            questions.append(q.question)
    
    page = request.GET.get('page', 1)
    paginator = Paginator(questions, 10)
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)
    
    context = {
        'questions': questions
        
    }
    
    return render(request, 'home/questions.html', context = context)



@login_required
@expert_required
def questions_details(request, pk):
    null_session(request)
    if 'extra' not in request.session:
        request.session['extra'] = 0
    
    res_question = get_object_or_404(Question, pk = pk)
    
    '''get questions related to the current user'''
    curent_user_expert_in = request.user.experts_in
    
    if request.user.is_staff or request.user.is_superuser:
        question = res_question
    else: 
    
        try:
            label_to_question = Label.objects.get(name = curent_user_expert_in, value = str(1), question = res_question)
            question = label_to_question.question
        except:
            raise PermissionDenied   
    
    
    OptionFormSet = inlineformset_factory(Question, Option, fk_name='question', form = OptionForm, extra= int(request.session['extra']), can_delete=False)

    if request.method == 'POST':
        question_form = QuestionForm(request.POST, request.FILES, prefix='questions', instance=question)
        
        option_formset = OptionFormSet(request.POST, request.FILES, prefix='options', instance=question)
        if question_form.is_valid() and option_formset.is_valid():
            question = question_form.save()
            option_formset = OptionFormSet(request.POST, request.FILES, prefix='options', instance=question)
            option_formset.is_valid()
            option_formset.save()
            request.session['extra'] = 0
            if 'add_more' in request.POST or 'extra' in request.POST:
                return HttpResponseRedirect(reverse('home:questions_details', args=[str(pk)]))
            else:
                return HttpResponseRedirect(reverse('home:questions'))
            
        else:
            return render(request, 'home/questions_details.html', {
                'question': question,
                'question_form': question_form,
                'option_formset': option_formset,
            })
            
    else:
        question_form = QuestionForm(prefix='questions', instance=question)
        option_formset = OptionFormSet(prefix='options', instance=question)
    
    
    
    context = {
        'question': question,
        'question_form': question_form,
        'option_formset': option_formset,
        
    }
    return render(request, 'home/questions_details.html', context = context)

@login_required
@expert_required
def new_questions(request):
    null_session(request)
    if 'extra' not in request.session:
        request.session['extra'] = 0
    OptionFormSet = inlineformset_factory(Question, Option, fk_name='question', form = OptionForm, extra= 3, can_delete=False)

    if request.method == 'POST':
        question_form = QuestionForm(request.POST, request.FILES, prefix='questions')
        
        option_formset = OptionFormSet(request.POST, request.FILES, prefix='options')
        if question_form.is_valid() and option_formset.is_valid():
            question = question_form.save()
            option_formset = OptionFormSet(request.POST, request.FILES, prefix='options', instance=question)
            option_formset.is_valid()
            option_formset.save()
            request.session['extra'] = 0
            if 'add_more' in request.POST or 'extra' in request.POST:
                return HttpResponseRedirect(reverse('home:questions_details', args=[str(question.id)]))
            else:
                return HttpResponseRedirect(reverse('home:questions'))
            
        else:
            return render(request, 'home/new_question.html', {
                
                'question_form': question_form,
                'option_formset': option_formset,
            })
            
    else:
        question_form = QuestionForm(prefix='questions')
        option_formset = OptionFormSet(prefix='options')
    
    
    
    context = {
        
        'question_form': question_form,
        'option_formset': option_formset,
        
    }

templates/home/new_question.html
{% extends "layouts/base.html" %}

{% block title %} New Question {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
    <div class="d-block mb-4 mb-md-0">
        <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
<!--
            <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
                <li class="breadcrumb-item">
                    <a href="#">
                        <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
                            </path>
                        </svg>
                    </a>
                </li>
                <li class="breadcrumb-item"><a href="#">Volt</a></li>
                <li class="breadcrumb-item active" aria-current="page">Transactions</li>
            </ol>
        -->
        </nav>
        <h2 class="h4">New Question</h2>
        <p class="mb-0">Green Fuel Validation Platform.</p>
    </div>
<!--
    <div class="btn-toolbar mb-2 mb-md-0">
        <a href="#" class="btn btn-sm btn-gray-800 d-inline-flex align-items-center">
            <svg class="icon icon-xs me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6">
                </path>
            </svg>
            New Plan
        </a>
        <div class="btn-group ms-2 ms-lg-3">
            <button type="button" class="btn btn-sm btn-outline-gray-600">Share</button>
            <button type="button" class="btn btn-sm btn-outline-gray-600">Export</button>
        </div>
    </div>
-->
</div>
<!--
<div class="table-settings mb-4">
    <div class="row align-items-center justify-content-between">
        <div class="col col-md-6 col-lg-3 col-xl-4">
            <div class="input-group me-2 me-lg-3 fmxw-400">
                <span class="input-group-text">
                    <svg class="icon icon-xs" x-description="Heroicon name: solid/search"
                        xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd"
                            d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                            clip-rule="evenodd"></path>
                    </svg>
                </span>
                <input type="text" class="form-control" placeholder="Search orders">
            </div>
        </div>
        <div class="col-4 col-md-2 col-xl-1 ps-md-0 text-end">
            <div class="dropdown">
                <button class="btn btn-link text-dark dropdown-toggle dropdown-toggle-split m-0 p-1"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z"
                            clip-rule="evenodd"></path>
                    </svg>
                    <span class="visually-hidden">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu dropdown-menu-xs dropdown-menu-end pb-0">
                    <span class="small ps-3 fw-bold text-dark">Show</span>
                    <a class="dropdown-item d-flex align-items-center fw-bold" href="#">10 <svg
                            class="icon icon-xxs ms-auto" fill="currentColor" viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                                clip-rule="evenodd"></path>
                        </svg></a>
                    <a class="dropdown-item fw-bold" href="#">20</a>
                    <a class="dropdown-item fw-bold rounded-bottom" href="#">30</a>
                </div>
            </div>
        </div>
    </div>
</div>
-->

<div class="card card-body border-0 shadow table-wrapper table-responsive">



    <div class="card card-head border-0 shadow mb-4 p-4">
        {{ question.name }}
    </div>

    <div hx-target="this" hx-swap="outerHTML">

        <form method="post" action="{% url 'home:new_question' %}">
            {% csrf_token %}

            {{ option_formset.management_form }}




            <div class="row">
                <div class="col-12 mb-3">
                    <div class="form-group mb-4">
                        <div class="row input-group">
                            {% for q_form in question_form %}
                            <div class="card card-body border-0 shadow mb-4">
                                {{ q_form }}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-12 mb-3">
                    <div class="form-group mb-4">
                        <div class="row input-group">
                            {% for form in option_formset %}
                            <div class="card card-body border-0 shadow mb-4">
                                {{ form }}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>



            <input class="btn btn-success btn-block" type="submit" name="add_more" hx-post="." id="add_more"
                value="Save and Stay">
            <input class="btn btn-success btn-block" type="submit" name="save" hx-post="." id="save" value="Save">

        </form>






    </div>









</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/home/questions_details.html
{% extends "layouts/base.html" %}

{% block title %} Question {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
    <div class="d-block mb-4 mb-md-0">
        <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
<!--
            <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
                <li class="breadcrumb-item">
                    <a href="#">
                        <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
                            </path>
                        </svg>
                    </a>
                </li>
                <li class="breadcrumb-item"><a href="#">Volt</a></li>
                <li class="breadcrumb-item active" aria-current="page">Transactions</li>
            </ol>
        -->
        </nav>
        <h2 class="h4">Question Edit</h2>
        <p class="mb-0">Green Fuel validation Platform.</p>
    </div>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a href="{% url 'home:new_question'  %}" class="btn btn-sm btn-gray-800 d-inline-flex align-items-center">
            <svg class="icon icon-xs me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6">
                </path>
            </svg>
            New Question
        </a>
        <!--
        <div class="btn-group ms-2 ms-lg-3">
            <button type="button" class="btn btn-sm btn-outline-gray-600">Share</button>
            <button type="button" class="btn btn-sm btn-outline-gray-600">Export</button>
        </div>
    -->
    </div>
</div>

<!--
<div class="table-settings mb-4">
    <div class="row align-items-center justify-content-between">
        <div class="col col-md-6 col-lg-3 col-xl-4">
            <div class="input-group me-2 me-lg-3 fmxw-400">
                <span class="input-group-text">
                    <svg class="icon icon-xs" x-description="Heroicon name: solid/search"
                        xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd"
                            d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                            clip-rule="evenodd"></path>
                    </svg>
                </span>
                <input type="text" class="form-control" placeholder="Search orders">
            </div>
        </div>
        <div class="col-4 col-md-2 col-xl-1 ps-md-0 text-end">
            <div class="dropdown">
                <button class="btn btn-link text-dark dropdown-toggle dropdown-toggle-split m-0 p-1"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z"
                            clip-rule="evenodd"></path>
                    </svg>
                    <span class="visually-hidden">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu dropdown-menu-xs dropdown-menu-end pb-0">
                    <span class="small ps-3 fw-bold text-dark">Show</span>
                    <a class="dropdown-item d-flex align-items-center fw-bold" href="#">10 <svg
                            class="icon icon-xxs ms-auto" fill="currentColor" viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                                clip-rule="evenodd"></path>
                        </svg></a>
                    <a class="dropdown-item fw-bold" href="#">20</a>
                    <a class="dropdown-item fw-bold rounded-bottom" href="#">30</a>
                </div>
            </div>
        </div>
    </div>
</div>
-->
<div class="card card-body border-0 shadow table-wrapper table-responsive">



    <div class="card card-head border-0 shadow mb-4 p-4">
        {{ question.name }}
    </div>

    <div hx-target="this" hx-swap="outerHTML">

        <form method="post" action="{% url 'home:questions_details' question.pk %}">
            {% csrf_token %}

            {{ option_formset.management_form }}




            <div class="row">
                <div class="col-12 mb-3">
                    <div class="form-group mb-4">
                        <div class="row input-group">
                            {% for q_form in question_form %}
                            <div class="card card-body border-0 shadow mb-4">
                                {{ q_form }}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-12 mb-3">
                    <div class="form-group mb-4">
                        <div class="row input-group">
                            {% for form in option_formset %}
                            <div class="card card-body border-0 shadow mb-4">
                                {{ form }}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>




            <button class="btn btn-success btn-block" hx-get="{% url 'home:add_extra' question.pk  %}" hx-target="#pppp"
                hx-swap="outerHTML" name="extra" hx-trigger="click">
                Add Extra
            </button>

            <button class="btn btn-success btn-block" hx-get="{% url 'home:sub_extra' question.pk  %}" hx-target="#pppp"
                hx-swap="outerHTML" name="extra" hx-trigger="click">
                Sub Extra
            </button>


            <input class="btn btn-success btn-block" type="submit" name="add_more" hx-post="." id="add_more"
                value="Save and Stay">
            <input class="btn btn-success btn-block" type="submit" name="save" hx-post="." id="save" value="Save">

        </form>






    </div>









</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}