crm/urls.py
from . import views

from django.urls import path
from django.views.generic.base import TemplateView


app_name = 'crm'

urlpatterns = [
    path('crm/leads', views.leads, name='leads'),
    path('crm/unsubscrib/<email>/<code>', views.unsubscrib, name='unsubscrib'),
    path('crm/subscrib/<str:email>', views.subscrib, name='subscrib'),
]

evaluation/urls.py
from django.urls import path
from . import views

app_name = 'evaluation'
urlpatterns = [
    path('evaluation/', views.eva_index, name='evaluation'),    
    path('evaluation/option_add/', views.option_add, name='option_add'),  
    path('evaluation/option_append/', views.option_append, name='option_append'),
    path('evaluation/thanks/', views.thanks, name='thanks'),      
    path('evaluation/report/<int:report_id>', views.report, name='report'),         
    
    
]

evaluation/models.py
from django.conf import settings
from django.db import models
from django.forms import ValidationError
# from accounts.models import User
from django.urls import reverse

def get_common_status(value):
    try:
        common_status_total = DifinedLabel.objects.filter(common_status = True).count()
        common_status = DifinedLabel.objects.get(common_status = True)
    except Exception:
        common_status_total = 0

    if common_status_total == int(1) and value == 1:
        raise ValidationError('A common status named "' + common_status.name +'" already exist! Only One common status allowed!')
    else:
        pass

class DifinedLabel(models.Model): 
    name = models.CharField(max_length=252)
    label = models.CharField(max_length=252, default='')
    adj = models.CharField(max_length=252, default='')
    common_status = models.BooleanField(default=False, validators=[get_common_status])

    sort_order = models.CharField(max_length=3, default=0)

    def __str__(self):
        return self.name

class Question(models.Model):
    name = models.CharField(max_length=252)
    sort_order = models.IntegerField(default=1)
    description = models.TextField()
    is_active = models.BooleanField(default=False)

    class Meta:
        ordering = ['sort_order']

    def __str__(self):
        return  '(' + str(self.sort_order) +') ' + self.name
    
    def get_absolute_url(self):        
        return reverse('home:questions_details', args=[str(self.pk)])
    @property
    def labels(self):
        return Label.objects.filter(question = self)
    
    

class Label(models.Model):
    name = models.ForeignKey(DifinedLabel, on_delete=models.PROTECT, related_name='dlabels', limit_choices_to={'common_status': False})
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='questions')
    value = models.CharField(max_length=1, default=0)

    def __str__(self):
        return self.name.name

class Option(models.Model):
    name = models.CharField(max_length=252)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='question')
    next_question = models.ForeignKey(Question, on_delete=models.SET_NULL, null = True, blank = True, related_name='next_question', limit_choices_to={'is_active': True})
    statement = models.TextField(null = True, blank = True,)
    next_step = models.TextField(null = True, blank = True,)
    overall = models.CharField(max_length=1, default=0)
    positive = models.CharField(max_length=1, default=0)
    dont_know = models.BooleanField(default=False)

    def __str__(self):
        return self.name + '(' + str(self.question.sort_order) + ')'

class LogicalString(models.Model):
    options = models.ManyToManyField(Option)
    text = models.TextField(null = True, blank = True,)
    overall = models.CharField(max_length=1, default=0)
    positive = models.CharField(max_length=1, default=0)

    def __str__(self):
        return self.text

class Lslabel(models.Model):
    name = models.ForeignKey(DifinedLabel, on_delete=models.PROTECT, related_name='ls_dlabels', limit_choices_to={'common_status': False})
    logical_string = models.ForeignKey(LogicalString, on_delete=models.CASCADE, related_name='logical_strings')
    value = models.CharField(max_length=1, default=0)

    def __str__(self):
        return self.name.name




class Biofuel(models.Model):
    name = models.CharField(max_length=252)
    

    def __str__(self):
        return self.name

class Evaluator(models.Model):
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='user')
    name = models.CharField(max_length=252)
    email = models.EmailField()
    phone = models.CharField(max_length=16)
    orgonization = models.CharField(max_length=252)
    biofuel = models.ForeignKey(Biofuel, on_delete=models.SET_NULL, null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True, null=True, blank=True, editable=True)
    report_genarated = models.BooleanField(default=False)
    

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('evaluation:report', args=[str(self.id)])

class Evaluation(models.Model):
    evaluator = models.ForeignKey(Evaluator, on_delete=models.RESTRICT, related_name='eva_evaluator')
    option = models.ForeignKey(Option, on_delete=models.RESTRICT, related_name='eva_option')
    question = models.ForeignKey(Question, on_delete=models.RESTRICT,null=True, blank=True, related_name='eva_question')
    

    def __str__(self):
        return self.evaluator.name

    @property
    def get_question_comment(self):
        eva_comment = EvaComments.objects.filter(question = self.question, evaluator = self.evaluator)
        return eva_comment


class EvaComments(models.Model):
    evaluator = models.ForeignKey(Evaluator, on_delete=models.RESTRICT, related_name='coment_evaluator')
    question = models.ForeignKey(Question, on_delete=models.RESTRICT, related_name='comment_question')
    comments = models.TextField(max_length=600)

    def __str__(self):
        return self.comments


class EvaLabel(models.Model):
    label = models.ForeignKey(DifinedLabel, on_delete=models.PROTECT, related_name='labels')
    evaluator = models.ForeignKey(Evaluator, on_delete=models.RESTRICT, related_name='evaluators')
    sort_order = models.CharField(max_length=3, default=0)
    create_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.label.name

class EvaLebelStatement(models.Model):
    evalebel = models.ForeignKey(EvaLabel, on_delete=models.PROTECT)
    question = models.ForeignKey(Question, on_delete=models.PROTECT, null=True, blank=True)
    option_id = models.CharField(max_length=252, null=True, blank=True)
    statement = models.TextField(blank=True, null=True)
    next_step = models.TextField(blank=True, null=True)
    positive = models.CharField(max_length=1, default=0)
    dont_know = models.BooleanField(default=False)
    assesment = models.BooleanField(default=False)
    evaluator = models.ForeignKey(Evaluator, on_delete=models.RESTRICT, related_name='s_evaluators', null=True)
    create_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.statement
class OptionSet(models.Model):
    option_list = models.CharField(max_length=252, unique = True)
    text = models.TextField()
    positive = models.CharField(max_length=1, default=0)
    overall = models.CharField(max_length=1, default=0)
    ls_id = models.CharField(max_length=252, default=0)


    def __str__(self):
        return str(self.option_list) + str(self.text)

evaluation/views.py
from django.shortcuts import render
from django.http.response import Http404, HttpResponse, HttpResponseRedirect
from .forms import *
from .models import *
from accounts.models import UserType
from django.contrib import messages
from django.urls import reverse
from django_xhtml2pdf.utils import generate_pdf
from django.db.models import Count
from . helper import label_assesment_for_donot_know, label_assesment_for_positive, overall_assesment_for_donot_know, overall_assesment_for_positive, get_current_evaluator
import random
from django.contrib.auth.decorators import login_required
from accounts.decorators import expert_required, producer_required, consumer_required
from gfvp import null_session
from django.core.exceptions import PermissionDenied


# def get_current_evaluator(request):
#     evaluator = Evaluator.objects.get(email = request.session['evaluator'])
#     return evaluator


@login_required
@producer_required
def eva_index(request):  
    
    null_session(request)
    try:
        session_evaluator = Evaluator.objects.get(id = request.session['evaluator'])
    except:
        session_evaluator = False

    if  (session_evaluator is False) or ('question' not in request.session):
        '''Catch Primary Data'''
        if request.method == "POST": 
            form = EvaluatorForm(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                email = form.cleaned_data['email'] 
                phone = form.cleaned_data['phone']
                orgonization = form.cleaned_data['orgonization']
                biofuel = form.cleaned_data['biofuel']

                new_evaluator = Evaluator(creator = request.user, name = name, email = email, phone = phone, orgonization = orgonization, biofuel = biofuel )
                new_evaluator.save()

                request.session['evaluator'] = new_evaluator.id

                first_question = Question.objects.filter(is_active=True).order_by('sort_order').first()
                '''note next question to ask'''
                request.session['question'] = first_question.id
                request.session['total_question'] = 0



                defined_label = DifinedLabel.objects.all()


                for dl in defined_label:
                    new_evalabel = EvaLabel(label = dl, evaluator = get_current_evaluator(request), sort_order=dl.sort_order)
                    new_evalabel.save()
                request.session['option'] = ''

                return HttpResponseRedirect(reverse('evaluation:evaluation'))

        else:
            if request.user.is_authenticated:
                type = UserType.objects.get(slug = request.user.type.slug )
                name = request.user.get_full_name
                email = request.user.email
                phone = request.user.phone
                orgonization = request.user.orgonization
            else:
                type = UserType.objects.get(slug = request.session['interested_in'] )
                name = ''
                email = ''
                phone = ''
                orgonization = ''
            initial_dict = {
            "type" : type,
            "email" : email,
            "phone":phone,
            "orgonization":orgonization,
            "name":name
            }
            form = EvaluatorForm(initial = initial_dict)
        total_ques = Question.objects.all().count()
        box_timing = f"Depending on how many answers you provide, the self assessment will take anywhere from {round(total_ques/10)} to {round(total_ques/3)} minutes. At the end of the assessment, a PDF report will be provided, which can be retrieved via the Dashboard at a later stage."
        
        
        
        
        

        context = {
        'form': form,
        'evaluator': False,
        'box_timing': box_timing
        
        
        }
        return render(request, 'evaluation/index.html', context = context)
    else:
        '''Catch Answers'''
        '''if option yet not submited for the question comments field should not active'''
        if 'active' not in request.session:
            request.session['active'] = ''
            
        question = Question.objects.get(id = request.session['question'])
        options = Option.objects.filter(question = question)
        evaluator_data = get_current_evaluator(request)
        total_ques = Question.objects.all().count() - request.session['total_question']
        try:
            selected_option = Option.objects.get(id = request.session['option'])
        except Exception as e:
            selected_option = ''
        eva_lebels = EvaLabel.objects.filter(evaluator = evaluator_data).order_by('sort_order')
        timing_text = f"Depending on how you are answering the questions may take {round(total_ques/6)} to {round(total_ques/2)} min."
        
        
        
        
        
        context = {
            'question': question,
            'optns': options,
            'evaluator': True,
            'evaluator_data': evaluator_data,
            'eva_lebels': eva_lebels,
            'selected_option': selected_option,
            'acive': request.session['active'],
            'total_question': request.session['total_question'],
            'qualified_rang' : 0,
            'timing_text': timing_text,
            
            

        }
        return render(request, 'evaluation/index.html', context = context)

@login_required
@producer_required
def option_add(request):
    null_session(request) 
    if request.method == 'POST':
        try:
            option_id = request.POST['option_id']
        except:
            messages.warning(request, 'Please select an option to continue!')
            return HttpResponseRedirect(reverse('evaluation:evaluation'))

        comment = request.POST['comment']
        question = Question.objects.get(id = request.session['question'])
        # evaluator = Evaluator.objects.get(email = request.session['evaluator'])
        new_eva_comment = EvaComments(evaluator = get_current_evaluator(request), question = question, comments = comment)
        new_eva_comment.save()

        request.session['option'] = option_id
        '''Field set to be disabled'''
        request.session['active'] = 'disabled'


        return HttpResponseRedirect(reverse('evaluation:evaluation'))
    

    

def Genarator(request, selected_option):
    question = selected_option.question
    set_labels = Label.objects.filter(question =  question, value = 1)

    for set_label in set_labels:
        defined_label = DifinedLabel.objects.get(name = set_label.name)
        eva_label = EvaLabel.objects.get(label = defined_label, evaluator = get_current_evaluator(request))
        new_evalebel_statement = EvaLebelStatement(evalebel = eva_label, option_id = selected_option.id, statement = selected_option.statement, next_step = selected_option.next_step, dont_know = selected_option.dont_know, question = selected_option.question, positive = selected_option.positive, evaluator =  get_current_evaluator(request))
        new_evalebel_statement.save()

        EvaLebelStatement.objects.filter(evalebel = eva_label, evaluator = get_current_evaluator(request), assesment = True).delete()

        summery_statement_do_not_know = EvaLebelStatement(evalebel = eva_label, statement = label_assesment_for_donot_know(request, eva_label),  evaluator =  get_current_evaluator(request), assesment = True)
        summery_statement_do_not_know.save()

        summery_statement_positive = EvaLebelStatement(evalebel = eva_label, statement = label_assesment_for_positive(request, eva_label),  evaluator =  get_current_evaluator(request), assesment = True)
        summery_statement_positive.save()

    logical_strings = LogicalString.objects.all()
    logical_options = []

    for logical_string in logical_strings:
        ls_id = logical_string.id
        text = logical_string.text
        overall = logical_string.overall
        positive = logical_string.positive
        sting_options = logical_string.options.all()
        option_list = []
        for s_o in sting_options:
            option_list.append(str(s_o.id))
        logical_options.append(option_list)

        try:
            '''
            edit if any changed
            '''
            option_set = OptionSet.objects.get(option_list = option_list)
            option_set.id = ls_id
            option_set.text = text
            option_set.overall = overall
            option_set.positive = positive
            option_set.save()
        except Exception as e:
            '''
            delete changed to re input
            '''
            lo_except_last = [x for x in logical_options if x != option_list]
            unmatched = [item for item in logical_options if not item in lo_except_last ]
            try:
                for u in unmatched:
                    OptionSet.objects.get(option_list = u).delete()
            except Exception as e:
                pass
            new_option_set = OptionSet(option_list = option_list, text = text, overall = overall , positive = positive, ls_id = ls_id )
            new_option_set.save()

    eva_statement = EvaLebelStatement.objects.filter(evaluator = get_current_evaluator(request))
    es_option_id = set()
    for es in eva_statement:
        es_option_id.add(es.option_id)
    eoi = list(es_option_id)

    defined_common_label = DifinedLabel.objects.get(common_status = True)
    eva_label_common = EvaLabel.objects.get(label = defined_common_label, evaluator = get_current_evaluator(request))

    EvaLebelStatement.objects.filter(evalebel = eva_label_common, evaluator =  get_current_evaluator(request), assesment = True).delete()

    summery_statement_do_not_know = EvaLebelStatement(evalebel = eva_label_common, statement = overall_assesment_for_donot_know(request, eva_label_common),  evaluator =  get_current_evaluator(request), assesment = True)
    summery_statement_do_not_know.save()

templates/evaluation/index.html
{% extends "includes/g_base.html" %}
<!DOCTYPE html>
<html lang="en">


<body>

    {% block header %}
    {% include 'includes/g_header.html' %}
    {% endblock %}


    {% block main %}
    <main id="xxxx">
        <div id="xxx">
            <div id="xx">

            

        
        <!-- Hero -->
        <section class="section-header overflow-hidden pt-7 pt-lg-8 pb-9 pb-lg-12 bg-primary text-white">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center">
                        <div class="bootstrap-big-icon d-none d-lg-block">
                            <svg xmlns="http://www.w3.org/2000/svg" width="700" height="622" class="d-block my-1"
                                viewBox="0 0 118 94" role="img">
                                <title>Green Fuel Validation Platform</title>
                                <path fill-rule="evenodd" clip-rule="evenodd"
                                    d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"
                                    fill="currentColor"></path>
                            </svg>
                        </div>
                        <h1 class="fw-bolder">Green Fuel Validation Platform</h1>
                        <h2 class="lead fw-normal text-muted mb-5">
                            Self assesment
                        </h2>


                    </div>
                </div>
            </div>
            <figure class="position-absolute bottom-0 left-0 w-100 d-none d-md-block mb-n2"><svg class="home-pattern"
                    xmlns="http://www.w3.org/2000/svg" viewBox="0 0 3000 185.4">
                    <path d="M3000,0v185.4H0V0c496.4,115.6,996.4,173.4,1500,173.4S2503.6,115.6,3000,0z"></path>
                </svg></figure>
        </section>
        <div  class="section pt-0">
            <div class="container mt-n10 mt-lg-n12 z-2">
                <div class="row justify-content-center">
                    <div class="col-12">
                        {% if evaluator == False %}
                        <div class="row d-flex justify-content-center ">
                            <div class="col-md-6 align-items-center ">
                                <div class="card p-3">
                                   
                                <form method="POST" >
                                    {% csrf_token %}
                                    {{form.as_p}}

                                    <div class="btn btn-success mt-3">Disclaimer: The green fuel validation platform
                                        and its partners cannot be held responsible for the veracity of the information
                                        provided in the self assessment.</div>

                                    <div class="btn btn-info mt-3 mb-3">
                                        {{ box_timing }}
                                    </div>
                                        <div class="mt-2 mb-2">
                                            <input type="checkbox" name="" id="" > <span> Please confirm terms and conditions</span>
                                        </div>
                                    
                                    <button type="submit" hx-post="." hx-target="#xxx" hx-indicator="#indicator2" hx-swap="outerHTML" id="btn_ini" class="btn btn-success btn-block">Submit</button>
                                    <span id="indicator2" class="htmx-indicator" > Processing.... </span>
                                </form>
                            
                            </div>
                            </div>
                        </div>
                        {% else %}
                        <div class="card text-center">
                            <div class="card-header">
                                {{ timing_text }}
                            </div>
                            <!--
                            <div class="card-header">
                                
                                Greenfuel Producer
                            </div>
                            
                            <div class="card-body">
                                <h4 class="card-title">Name: {{evaluator_data.name}}</h4>
                                <h5 class="card-title">Email: {{evaluator_data.email}}</h5>
                                <h6 class="card-title">Phone: {{evaluator_data.phone}}</h6>
                                <p class="card-text">Organization: {{evaluator_data.orgonization}}</p>
                            </div>
                        -->
                            <div class="card-footer">
                                <h3>Question: {{question.name}}</h3>                                
                            </div>
                            <div class="card-footer">
                                {% if question.description %}
                                <p>{{question.description}}</p>
                                {% else %}
                                <p>Description of the question are coming soon in this place!</p>
                                {% endif %}
                            </div>
                        </div>
                        {% if total_question <= qualified_rang %}
                        {% if messages %}
                        
                        <div class="alert alert-secondary mt-5" role="alert">
                            {% for message in messages %}
                            <span class="alert-inner--text">{{ message }}</span>
                            {% endfor %}
                        </div>
                        
                        {% endif %}
                        {% endif %}
                        <div class="row mt-5 mb-10">
                            <div class="col-sm-6">
                                <div class="card">
                                    <div class="card-body">
                                        <h5>Options:</h5>
                                        <form method="POST" >
                                            {% csrf_token %}
                                            {% for optn in optns %}                                          
                                                                                               
                                            <fieldset>                                                
                                                <div class="form-check">                                                    
                                                    <input class="form-check-input" type="radio" name="option_id" id="{{optn.id}}" value="{{optn.id}}" {% if optn.id == selected_option.id %} checked {% endif %} required>
                                                    <label class="form-check-label" for="{{optn.id}}"> {{optn.name}}                                                        
                                                    </label>  
                                                </div>
                                            </fieldset>  
                                            {% endfor %}
                                            <h5>Your Comments Here:</h5>
                                            <div class="mt-3">
                                                <textarea class="form-control" id="comment" name="comment"></textarea>
                                            </div>
                                            <div class="mt-3">
                                                <button type="submit"  hx-post="{% url 'evaluation:option_add' %}" hx-indicator="#indicator1" hx-target="#xx" hx-swap="outerHTML" value="Submit" class="btn btn-success btn-block"
                                                    >Submit </button>
                                                    <span id="indicator1" class="htmx-indicator" > Processing.... </span>
                                            </div>
                                        </form>
                                    
                                    
                                        <div class="mt-3">
                                            <h5>Feedback:</h5>
                                            <textarea class="form-control" id="feedback" rows="6" disabled> {{selected_option.statement}}</textarea>
                                        </div>
                                        <div class="mt-3">
                                            <!--
                                            <a class="btn btn-success btn-block"
                                                href="{%  url 'evaluation:option_append' %}">Confirm</a>
                                            -->

                                                <button class="btn btn-success btn-block" hx-get="{%  url 'evaluation:option_append' %}"
                                                hx-indicator="#indicator"
                                                hx-trigger="click"
                                                hx-target="#xxxx"
                                                hx-swap="outerHTML">
                                             Confirm
                                           </button>
                                           <span id="indicator" class="htmx-indicator" > Processing.... </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="alert alert-success" role="alert">
                                    Greenfuel Summary
                                </div>
                                <div class="card">
                                    <div class="card-body">
{% for eva_lebel in eva_lebels %}
{{eva_lebel.label.label}}
<textarea name="tarea" class="form-control" rows="6" id="floatingTextarea" disabled>
{% if total_question >= qualified_rang %}{% for el in eva_lebel.evalebelstatement_set.all %}
{{el.statement.strip}} 
{{el.next_step.strip}}{% endfor %}{% else %}Need to submit minimum {{ qualified_rang }} qualified ans to view your results! Current is {{ total_question }} !{% endif %}</textarea>{% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

    </main>

    {% endblock %}

    {% block footer %}
    <!--
    {% include 'includes/g_footer.html' %}
    -->
    {% endblock %}



</body>

</html>